language: node_js
node_js:
  - "6"
  - "6.1"
  - "5"
  - "5.11"
  - "5.10"
  - "5.9"
  - "5.8"
  - "5.7"
  - "5.6"
  - "5.5"
  - "5.4"
  - "5.3"
  - "5.2"
  - "5.1"
services:
  - redis-server
  - mysql