
environment:
  matrix:
    - nodejs_version: "6"
    - nodejs_version: "6.1"
    - nodejs_version: "5"
    - nodejs_version: "5.11"
    - nodejs_version: "5.10"
    - nodejs_version: "5.9"
    - nodejs_version: "5.8"
    - nodejs_version: "5.7"
    - nodejs_version: "5.6"
    - nodejs_version: "5.5"
    - nodejs_version: "5.4"
    - nodejs_version: "5.3"
    - nodejs_version: "5.2"
    - nodejs_version: "5.1"
services:
  - mysql
cache:
  - node_modules
install:
  - ps: Install-Product node $env:nodejs_version
  - cmd: nuget install redis-64 -excludeversion
  - cmd: redis-64\redis-server.exe --service-install
  - cmd: redis-64\redis-server.exe --service-start
  - if exist node_modules npm prune
  - if exist node_modules npm rebuild
  - npm install
build: off
test_script:
  - node --version
  - npm --version
  - npm run test
version: "{build}"