init:
  - git config --global core.autocrlf input

environment:
  matrix:
    - nodejs_version: "8.10.0"

services:
  - mysql
install:
  - ps: Install-Product node $env:nodejs_version
  - npm install npm@next
  - cmd: nuget install redis-64 -excludeversion
  - cmd: redis-64\tools\redis-server.exe --service-install
  - cmd: redis-64\tools\redis-server.exe --service-start
  # - if exist node_modules node_modules\.bin\npm prune
  # - if exist node_modules node_modules\.bin\npm rebuild
  - node_modules\.bin\npm install
test_script:
  - node --version
  - node_modules\.bin\npm --version
  - set NODE_ENV=test
  - set CONFIG_FILE=config/config.testwin.js
  - node_modules\.bin\npm run test-win
build: off
version: "{build}"
